<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN"
        "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" lang="<?=config::website_language ?? 'en' ?>">
<head>
    <meta charset="UTF-8" >
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">
    <meta http-equiv="Content-Language" content="<?=config::website_language ?? 'en-gb' ?>" />
    <title><?=$pageTitle ?></title>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
</head>
<body>
<div id="container">
    <div class="section">
        <h1>Admin Layout</h1>
        <hr />
        <?=$pageContent ?>
    </div>
</div>
</body>
</html>